[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin=lib/openzeppelin-contracts', '@openzeppelin-upgrades=lib/openzeppelin-contracts-upgradeable', '@chainlink=lib/chainlink/contracts']
optimizer = true
optimizer_runs = 2_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config