[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin=lib/openzeppelin-contracts', '@openzeppelin-upgrades=lib/openzeppelin-contracts-upgradeable', '@chainlink=lib/chainlink/contracts', '@aave=lib/aave-v3-core/contracts']
optimizer = true
optimizer_runs = 2_000
fs_permissions = [{ access = "read", path = "./"}]


[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"
